name: Deploy via SSH

on:
  push:
    branches: [could_it_be_stable_branch]
    # TODO: Add condition
    # on pull_request merged on stable
    # with tag :deploy:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: './*'
          remote_path: ${{ secrets.REMOTE_DIR }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: execute aplication on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: 'PATH="$PATH:$HOME/npm/bin"; cd ${{ secrets.REMOTE_DIR }}; yarn; yarn build; yarn start:prod -f'
